library(fmsb)

#' Create Radar Chart without Country Data
#'
#' This function generates a radar chart using the given dataset excluding the country data
#' (total_cost, observation_count, social_perception, health_impact, ecosystem_impact, ecology_impact, reversibility_impact).
#'
#' @param data A data frame or tibble containing the required columns:
#'   total_cost, observation_count, social_perception, health_impact, ecosystem_impact, ecology_impact, reversibility_impact
#'
#' @return A radar chart object generated by the fmsb::radarchart function.
#'
#' @import fmsb
#' @import dplyr
#' @export
create_radar_chart <- function(combined_data) {
   radar_data_1 <- combined_data %>%
    dplyr::select(
      Total_Cost_Billion_USD, Total_Observations, Social_Perception, Health_Impact, Ecosystem_Impact, Ecology_Impact, Reversibility_Impact
    )

  radar_data_1 <- radar_data_1 %>%
    dplyr::mutate(
      Social_Perception = as.numeric(convert_social_perception(Social_Perception)),
      Health_Impact = as.numeric(convert_health_impact(Health_Impact)),
      Ecosystem_Impact = as.numeric(convert_ecosystem_impact(Ecosystem_Impact)),
      Ecology_Impact = as.numeric(convert_ecological_impact(Ecology_Impact)),
      Reversibility_Impact = as.numeric(convert_reversibility_impact(Reversibility_Impact)),
      Total_Observations = get_abundance_type(Total_Observations, "numeric")
    )
  deneme <- as.vector(unlist(radar_data_1[1,]))

  # Add min/max rows for scaling the radar chart
  radar_data_1 <- rbind(rep(10, ncol(radar_data_1)), rep(0, ncol(radar_data_1)), radar_data_1)



  # Plot Radar Chart 1
  radarchart(radar_data_1, axistype = 1,
             pcol = "blue", pfcol = rgb(0.1, 0.6, 0.1, 0.3), plwd = 4, plty = 1,
             title = "Radar Chart 1: Total Cost and Total Observation")
  return(deneme)
}


#' Create Radar Chart with Country Data
#'
#' This function generates a radar chart using the given dataset including country data
#' (cost_by_country, obs_by_country, social_perception, health_impact, ecosystem_impact, ecology_impact, reversibility_impact).
#'
#' @param data A data frame or tibble containing the required columns:
#'   cost_by_country, obs_by_country, social_perception, health_impact, ecosystem_impact, ecology_impact, reversibility_impact
#'
#' @return A radar chart object generated by the fmsb::radarchart function.
#'
#' @import fmsb
#' @import dplyr
#' @export
create_country_radar_chart <- function(combined_data) {
  radar_data_2 <- combined_data %>%
    dplyr::select(
      Country_Cost_Billion_USD, Country_Observations, Social_Perception, Health_Impact, Ecosystem_Impact, Ecology_Impact, Reversibility_Impact
    )

  # abundance_impact = abundance_impact,
  # abundance_impact_country = abundance_impact_country

  radar_data_2 <- radar_data_2 %>%
    mutate(
      Social_Perception = convert_social_perception(Social_Perception),
      Health_Impact = convert_health_impact(Health_Impact),
      Ecosystem_Impact = convert_ecosystem_impact(Ecosystem_Impact),
      Ecology_Impact = convert_ecological_impact(Ecology_Impact),
      Reversibility_Impact = convert_reversibility_impact(Reversibility_Impact),
      Country_Observations = get_abundance_type(Country_Observations, "numeric")
    )
  deneme <- as.vector(unlist(radar_data_2[1,]))


  # Add min/max rows for scaling the radar chart
  radar_data_2 <- rbind(rep(10, ncol(radar_data_2)), rep(0, ncol(radar_data_2)), radar_data_2)

  # Plot Radar Chart 2
  radarchart(radar_data_2, axistype = 1,
             pcol = "red", pfcol = rgb(0.6, 0.1, 0.1, 0.3), plwd = 4, plty = 1,
             title = "Radar Chart 2: Total Cost and Total Observation in Selected Country")
  return(deneme)
}



#' Calculate the Area of a Radar Chart
#'
#' This function calculates the area enclosed by a radar chart using the Shoelace Theorem.
#' It computes the area of the polygon formed by the normalized values on the radar chart's axes.
#' The area is returned as a numeric value, representing the extent of the data in relation to
#' the maximum possible values.
#'
#' @param values A numeric vector of values, typically normalized between 0 and 1, representing
#'   the data points for each axis of the radar chart.
#'
#' @return A numeric value representing the area enclosed by the radar chart. The area will be
#'   between 0 and the maximum possible area, where all values are equal to 1.
#'
#' @details
#' The Shoelace Theorem is used to calculate the area of a polygon given its vertices. The function
#' assumes that the values are normalized to [0, 1], with 1 representing the maximum possible value
#' for each axis.
#'
#' @examples
#' # Example usage:
#' values <- c(0.8, 0.7, 0.9, 0.5, 0.6)
#' area <- calculate_radar_area(values)
#' print(area)  # Output the area of the radar chart
#'
#' @export
calculate_radar_area <- function(values) {
  n <- length(values)

  # Repeat the first value at the end of the vector to close the polygon
  values <- c(values, values[1])

  # Calculate the x and y coordinates of each point on the radar chart
  theta <- seq(0, 2 * pi, length.out = n + 1)
  x <- values * cos(theta)
  y <- values * sin(theta)

  # Shoelace theorem to calculate the area of the polygon
  area <- 0.5 * abs(sum(x[-(n+1)] * y[-1] - x[-1] * y[-(n+1)]))

  return(area)
}

